spring:
   # Database
  datasource:
    url: jdbc:postgresql://dpg-civfc4tiuiedpv01lnmg-a.oregon-postgres.render.com:5432/listajorgedb_73b6
    driver-class-name: org.postgresql.Driver
    username: jorge
    password: aVsbxZCY1br3dB98p9Eg8BeI6BM5Le4O
 
  # JPA properties
  jpa:
    show-sql: true
    hibernate.ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    generate-ddl: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true

logging:
  level:
    root: INFO
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
      