spring:
   # Database
  datasource:
    url: jdbc:mysql://localhost:3306/pacientes-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    
  # JPA properties
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        enable_lazy_load_no_trans: true
        
logging:
  level:
    root: INFO
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE