spring:
   # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-civfc4tiuiedpv01lnmg-a.oregon-postgres.render.com:5432/listajorgedb_73b6
    username: jorge
    password: aVsbxZCY1br3dB98p9Eg8BeI6BM5Le4O
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

logging:
  level:
    root: INFO
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE